name: Run Bun Format

on:
  workflow_dispatch: # allows manual triggering from the Actions tab

jobs:
  format:
    name: Run bun run format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Bun Install
        run: bun install
        
      - name: Run formatter
        run: bun run format
